#to understand how it works, think that it is on the epos folder... like trunk/auto_batch_comp.sh
echo Remember to enable the Monitor and previously set the Monitor frequencies at $1 traits!!

array=("COMMITED_INSTRUCTIONS" "UNHALTED_REFERENCE_CYCLES_SB" "CPU_CYCLES" "BRANCHES" "BRANCH_MISSES" "L1_CACHE_HITS" "L2_CACHE_HITS" "L3_CACHE_HITS_SB" "L3_CACHE_MISSES" "L1I_CACHE_MISS" "L1I_TLB_MISS" "PREDICTABLE_BRANCHES" "L1D_WRITEBACK" "L2D_WRITEBACK" "MEM_UOP_RETIRED_ALL_SB" "L1D_EVICTION_SB" "IDQ_UOPS_NOT_DELIVERED_CORE_SB" "IDQ_EMPTY_SB" "BR_MISP_EXEC_RETURN_NEAR_SB" "FP_COMP_OPS_EXE_X87_SB" "DTLB_STORE_MISSES_WALK_DURATION_SB" "DTLB_LOAD_MISSES_MISS_WALK_DURATION_SB" "BR_INST_EXEC_RETURN_NEAR_SB" "RESOURCE_STALLS_SB_SB" "XSNP_HIT_SB" "BR_MISP_EXEC_INDIRECT_JMP_NON_CALL_RET_SB" "BR_MISP_RETIRED_CONDITIONAL_SB" "LD_BLOCKS_DATA_UNKNOWN_SB" "LD_BLOCKS_STORE_FORWARD_SB" "LD_BLOCKS_NO_SR_SB" "LD_BLOCKS_ALL_BLOCK_SB" "MISALIGN_MEM_REF_LOADS_SB" "MISALIGN_MEM_REF_STORES_SB" "LD_BLOCKS_PARTIAL_ADDRESS_ALIAS_SB" "LD_BLOCKS_PARTIAL_ALL_STA_BLCOK_SB" "DTLB_LOAD_MISSES_MISS_CAUSES_A_WALK_SB" "DTLB_LOAD_MISSES_MISS_WALK_COMPLETED_SB" "DTLB_LOAD_MISSES_MISS_STLB_HIT_SB" "INT_MISC_RECOVERY_CYCLES_SB" "INT_MISC_RAT_STALL_CYCLES_SB" "UOPS_ISSUED_ANY_SB" "FP_COMP_OPS_EXE_SSE_FP_PACKED_DOUBLE_SB" "FP_COMP_OPS_EXE_SSE_FP_SCALAR_SINGLE_SB" "FP_COMP_OPS_EXE_SSE_PACKED_SINGLE_SB" "FP_COMP_OPS_EXE_SSE_SCALAR_DOUBLE_SB" "SIMD_FP_256_PACKED_SINGLE_SB" "SIMD_FP_256_PACKED_DOUBLE_SB" "ARITH_FPU_DIV_ACTIVE_SB" "INSTS_WRITTEN_TO_IQ_INSTS_SB" "L2_RQSTS_DEMAND_DATA_RD_HIT_SB" "L2_RQSTS_ALL_DEMAND_DATA_RD_SB" "L2_RQSTS_RFO_HITS_SB" "L2_RQSTS_RFO_MISS_SB" "L2_RQSTS_ALL_RFO_SB" "L2_RQSTS_CODE_RD_HIT_SB" "L2_RQSTS_CODE_RD_MISS_SB" "L2_RQSTS_ALL_CODE_RD_SB" "L2_RQSTS_PF_HIT_SB" "L2_RQSTS_PF_MISS_SB" "L2_RQSTS_ALL_PF_SB" "L2_STORE_LOCK_RQSTS_MISS_SB" "L2_STORE_LOCK_RQSTS_HIT_E_SB" "L2_STORE_LOCK_RQSTS_HIT_M_SB" "L2_STORE_LOCK_RQSTS_ALL_SB" "L2_L1D_WB_RQSTS_HIT_E_SB" "L2_L1D_WB_RQSTS_HIT_M_SB" "L2_TRANS_DEMAND_DATA_RD_SB" "L2_TRANS_RFO_SB" "L2_TRANS_CODE_RD_SB" "L2_TRANS_ALL_PF_SB" "L2_TRANS_L2_FILL_SB" "L2_TRANS_ALL_REQ_UESTS_SB" "L2_LINES_IN_I_SB" "L2_LINES_IN_S_SB" "L2_LINES_IN_E_SB" "L2_LINES_IN_ALL_SB" "L2_LINES_OUT_DEMAND_CLEAN_SB" "L2_LINES_OUT_DEMAND_DIRTY_SB" "L2_LINES_OUT_DEMAND_PF_CLEAN_SB" "L2_LINES_OUT_DEMAND_PF_DIRTY_SB" "L2_LINES_OUT_DEMAND_DIRTY_ALL_SB" "LONGEST_LAT_CACHE_REFERENCE_SB" "LONGEST_LAT_CACHE_MISS_SB" "CPU_CLK_UNHALTED_THREAD_P_SB" "CPU_CLK_THREAD_UNHALTED_REF_XCLK_SB" "L1D_PEND_MISS_PENDING_SB" "DTLB_STORE_MISSES_MISS_CAUSES_A_WALK_SB" "DTLB_STORE_MISSES_WALK_COMPLETED_SB" "DTLB_STORE_MISSES_TLB_HIT_SB" "LOAD_HIT_PRE_SW_PF_SB" "LOAD_HIT_PREHW_PF_SB" "HW_PRE_REQ_DL1_MISS_SB" "L1D_REPLACEMENT_SB" "L1D_ALLOCATED_IN_M_SB" "L1D_ALL_M_REPLACEMENT_SB" "PARTIAL_RAT_STALLS_FLAGS_MERGE_UOP_SB" "PARTIAL_RAT_STALLS_SLOW_LEA_WINDOW_SB" "PARTIAL_RAT_STALLS_MUL_SINGLE_UOP_SB" "RESOURCE_STALLS2_ALL_FL_EMPTY_SB" "RESOURCE_STALLS2_ALL_PRF_CONTROL_SB" "RESOURCE_STALLS2_BOB_FULL_SB" "RESOURCE_STALLS2_OOO_RSRC_SB" "CPL_CYCLES_RING0_SB" "CPL_CYCLES_RING123_SB" "RS_EVENTS_EMPTY_CYCLES_SB" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD_SB" "OFFCORE_REQUESTS_OUTSTANDING_DEMAND_RFO_SB" "OFFCORE_REQUESTS_OUTSTANDING_ALL_DATA_RD_SB" "LOCK_CYCLES_SPLIT_LOCK_UC_LOCK_DURATION_SB" "LOCK_CYCLES_CACHE_LOCK_DURATION_SB" "IDQ_MITE_UOPS_SB" "IDQ_DSB_UOPS_SB" "IDQ_MS_DSB_UOPS_SB" "IDQ_MS_MITE_UOPS_SB" "IDQ_MS_UOPS_SB" "ITLB_MISSES_MISS_CAUSES_A_WALK_SB" "ITLB_MISSES_WALK_COMPLETED_SB" "ITLB_MISSES_WALK_DURATION_SB" "ITLB_MISSES_STLB_HIT_SB" "ILD_STALL_LCP_SB" "ILD_STALL_IQ_FULL_SB" "BR_INST_EXEC_DIRECT_JMP_SB" "BR_INST_EXEC_INDIRECT_JMP_NON_CALL_RET_SB" "BR_INST_EXEC_DIRECT_NEAR_CALL_SB" "BR_INST_EXEC_INDIRECT_NEAR_CALL_SB" "BR_INST_EXEC_NON_TAKEN_SB" "BR_INST_EXEC_TAKEN_SB" "BR_INST_EXEC_ALL_BRANCHES_SB" "BR_MISP_EXEC_COND_SB" "BR_MISP_EXEC_DIRECT_NEAR_CALL_SB" "BR_MISP_EXEC_INDIRECT_NEAR_CALL_SB" "BR_MISP_EXEC_NON_TAKEN_SB" "BR_MISP_EXEC_TAKEN_SB" "BR_MISP_EXEC_ALL_BRANCHES_SB" "UOPS_DISPATCHED_PORT_PORT_0_SB" "UOPS_DISPATCHED_PORT_PORT_1_SB" "UOPS_DISPATCHED_PORT_PORT_2_LD_SB" "UOPS_DISPATCHED_PORT_PORT_2_STA_SB" "UOPS_DISPATCHED_PORT_PORT_2_SB" "UOPS_DISPATCHED_PORT_PORT_3_LD_SB" "UOPS_DISPATCHED_PORT_PORT_3_STA_SB" "UOPS_DISPATCHED_PORT_PORT_3_SB" "UOPS_DISPATCHED_PORT_PORT_4_SB" "UOPS_DISPATCHED_PORT_PORT_5_SB" "RESOURCE_STALLS_ANY_SB" "RESOURCE_STALLS_LB_SB" "RESOURCE_STALLS_RS_SB" "RESOURCE_STALLS_ROB_SB" "RESOURCE_STALLS_FCSW_SB" "RESOURCE_STALLS_MXCSR_SB" "RESOURCE_STALLS_OTHER_SB" "DSB2MITE_SWITCHES_COUNT_SB" "DSB2MITE_SWITCHES_PENALTY_CYCLES_SB" "DSB_FILL_OTHER_CANCEL_SB" "DSB_FILL_EXCEED_DSB_LINES_SB" "DSB_FILL_ALL_CANCEL_SB" "ITLB_ITLB_FLUSH_SB" "OFFCORE_REQUESTS_DEMAND_DATA_RD_SB" "OFFCORE_REQUESTS_DEMAND_RFO_SB" "OFFCORE_REQUESTS_ALL_DATA_RD_SB" "UOPS_DISPATCHED_THREAD_SB" "UOPS_DISPATCHED_CORE_SB" "OFFCORE_REQUESTS_BUFFER_SQ_FULL_SB" "AGU_BYPASS_CANCEL_COUNT_SB" "OFF_CORE_RESPONSE_0_SB" "OFF_CORE_RESPONSE_1_SB" "TLB_FLUSH_DTLB_THREAD_SB" "TLB_FLUSH_STLB_ANY_SB" "L1D_BLOCKS_BANK_CONFLICT_CYCLES_SB" "INST_RETIRED_ANY_P_SB" "INST_RETIRED_PREC_DIST_SB" "OTHER_ASSISTS_AVX_STORE_SB" "OTHER_ASSISTS_AVX_TO_SSE_SB" "OTHER_ASSISTS_SSE_TO_AVX_SB" "UOPS_RETIRED_ALL_SB" "UOPS_RETIRED_RETIRE_SLOTS_SB" "MACHINE_CLEARS_MEMORY_ORDERING_SB" "MACHINE_CLEARS_SMC_SB" "MACHINE_CLEARS_MASKMOV_SB" "BR_INST_RETIRED_ALL_BRANCHES_ARCH_SB" "BR_INST_RETIRED_CONDITIONAL_SB" "BR_INST_RETIRED_NEAR_CALL_SB" "BR_INST_RETIRED_ALL_BRANCHES_SB" "BR_INST_RETIRED_NEAR_RETURN_SB" "BR_INST_RETIRED_NOT_TAKEN_SB" "BR_INST_RETIRED_NEAR_TAKEN_SB" "BR_INST_RETIRED_FAR_BRANCH_SB" "BR_MISP_RETIRED_ALL_BRANCHES_ARCH_SB" "BR_MISP_RETIRED_NEAR_CALL_SB" "BR_MISP_RETIRED_ALL_BRANCHES_SB" "BR_MISP_RETIRED_NOT_TAKEN_SB" "BR_MISP_RETIRED_TAKEN_SB" "FP_ASSIST_X87_OUTPUT_SB" "FP_ASSIST_X87_INPUT_SB" "FP_ASSIST_SIMD_OUTPUT_SB" "FP_ASSIST_SIMD_INPUT_SB" "FP_ASSIST_ANY_SB" "ROB_MISC_EVENTS_LBR_INSERTS_SB" "MEM_TRANS_RETIRED_LOAD_LATENCY_SB" "MEM_TRANS_RETIRED_PRECISE_STORE_SB" "MEM_UOP_RETIRED_LOADS_SB" "MEM_UOP_RETIRED_STORES_SB" "MEM_UOP_RETIRED_STLB_MISS_SB" "MEM_UOP_RETIRED_LOCK_SB" "MEM_UOP_RETIRED_SPLIT_SB" "MEM_UOPS_RETIRED_ALL_LOADS_SB" "MEM_LOAD_UOPS_RETIRED_L3_HIT_SB" "MEM_LOAD_UOPS_RETIRED_HIT_LFB_SB" "XSNP_MISS_SB" "XSNP_HITM_SB" "XSNP_NONE_SB" "MEM_LOAD_UOPS_MISC_RETIRED_LLC_MISS_SB" "SQ_MISC_SPLIT_LOCK_SB")

((counter = 0+1))

old1="${array[0]}"
old2="${array[1]}"
old3="${array[2]}"
old4="${array[3]}"
old5="${array[4]}"
old6="${array[5]}"
old7="${array[6]}"

temp1="${array[7]}"
temp2="${array[8]}"
temp3="${array[9]}"
temp4="${array[10]}"

sed -i 's/{'$old1','$old2','$old3','$old4','$old5','$old6','$old7'};/{'$temp1','$temp2','$temp3','$temp4'};/' ./app/$1/$1_traits.h
echo INIT
make veryclean >> ./../out/clean$counter.txt && make APPLICATION=$1 >> ./../out/comp$counter.txt
cp ./img/$1.img ./../imgs/epos0$counter.img

old1=$temp1
old2=$temp2
old3=$temp3
old4=$temp4

echo $old1 $old2 $old3 $old4
echo END 1

((counter = 1+1))
while [ $counter -lt 52 ]
do
	((temp = $counter*4+3))
	temp1="${array[$temp]}"
	temp2="${array[$temp+1]}"
	temp3="${array[$temp+2]}"
	temp4="${array[$temp+3]}"

	sed -i 's/{'$old1','$old2','$old3','$old4'};/{'$temp1','$temp2','$temp3','$temp4'};/' ./app/$1/$1_traits.h

	old1=$temp1
	old2=$temp2
	old3=$temp3
	old4=$temp4

	echo $old1 $old2 $old3 $old4

    make veryclean >> ./../out/clean$counter.txt && make APPLICATION=$1 >> ./../out/comp$counter.txt
    if [ $counter -lt 10 ]
    then
        cp ./img/$1.img ./../imgs/epos0$counter.img
    else
        cp ./img/$1.img ./../imgs/epos$counter.img
    fi
    echo "END" $counter
    ((counter = $counter + 1))
done
((temp = 211+0))
temp1="${array[$temp]}" #211
temp2="${array[$temp+1]}" #212
#temp3="${array[$temp+2]}"
#temp4="${array[$temp+3]}"
echo $temp1 $temp2 $temp3 $temp4
sed -i 's/{'$old1','$old2','$old3','$old4'};/{'$temp1','$temp2','$temp3','$temp4'};/' ./app/$1/$1_traits.h

old1=$temp1
old2=$temp2
old3=$temp3
old4=$temp4
make veryclean >> ./../out/clean$counter.txt && make APPLICATION=$1 >> ./../out/comp$counter.txt
cp ./img/$1.img ./../imgs/epos$counter.img
echo "END" $counter
#scp ./../imgs/*.img entropy_proxy:/var/ftpd/imgs/
#scp ./img/hello.img entropy_proxy:/var/ftpd/epos.img
