# EPOS Transducer Makefile

include ../../makedefs

#OBJS := $(subst .cc,.o,$(shell find *.cc | grep -v _init | grep -v _test))
#INITS := $(subst .cc,.o,$(shell find *.cc | grep _init))

all:		#$(LIBMACH) # $(LIBINIT)

#$(LIBMACH):	$(LIBMACH)($(OBJS))	

#$(LIBINIT):	$(LIBINIT)($(INITS))

clean:
		$(CLEAN) *.o
